// COLORS®: every colour GOOD® has released, shown on colors.html.
// Keep this list up to date: whenever a new colour ships (a shirt or pants
// colourway, a wash, a shoe, a DEEP END® look), add it here.
// hex = the colour (two for colours that are always worn as a pair);
// where = what it's used in; desc = the description shown on the page.
// Colour names are trademarked (™, added on the page), not registered (®);
// GOOD® itself always stays GOOD®. pantone = a PANTONE® colour: credited on
// the page and in the modal, and not marked ™ (the name is Pantone's).
window.GOOD_COLORS = [
  { name: 'GOOD® BLUE', hex: '#0000ff', where: 'SHIRT®, CROPPIE®, DOUBBIE®, SMILEY®, GOODIE®, G-KNIT®, COLLAR®, SNEAK01 sole, BABY TEE®, HALTER®, CORSET®, CROPPED PUFFER®', desc: 'Our flagship, and the purest blue we could make. Calm but electric, modern but timeless. It can be imitated, never replicated. This is GOOD® at its most distilled, the version we\'ll always be chasing.' },
  { name: 'COTTON', hex: '#ffffff', where: 'SHIRT®, CROPPIE®, DOUBBIE®, SMILEY®, GOODIE®, G-KNIT®, COLLAR®, BABY TEE®, HALTER®, CORSET®', desc: 'A clean blend of whites and soft greys, native to the fabric itself. Rendered here as Clean White: the blank page every piece starts from.' },
  { name: 'DENIM', hex: '#57b3ea', where: 'SHIRT® COTTON/DENIM, COLLAR® COTTON/DENIM, DOUBBIE® DUST PINK (tee logo)', desc: 'Second only to SPRINGSTEEN™, and our favorite take on the perfect wash. Not too dark, not too light. Just (almost) right.' },
  { name: 'BLAUE', hex: '#2468ff', where: 'SHIRT® BLAUE/COTTON', desc: 'Named for the Blaue Blume, the blue flower the Romantics chased as a symbol of longing and inspiration. Vivid and alive, like the first wildflowers of spring in an overgrown garden.' },
  { name: 'DUST PINK', hex: '#c98aa0', where: 'CROPPIE®, DOUBBIE® and G-KNIT® DUST PINK/TOMATO VINE, BABY TEE®', desc: 'A sleepy, warm pink, soft at the edges like late-afternoon light. One of our favorites, and one we hold close.' },
  { name: 'TOMATO VINE', hex: '#3f7a55', where: 'CROPPIE®, DOUBBIE® and G-KNIT® DUST PINK/TOMATO VINE, CARDIE®, BABY TEE®, WATERMELONS®', desc: 'Earthy and punchy, with a little tang. The green of things still growing: stems, leaves, and a garden mid-season.' },
  { name: 'PUMPKIN', hex: '#fda327', where: 'SMILEY® PUMPKIN/NEON', desc: 'Fall, distilled. As leaves tumble to the ground, let this one remind you of the earth turning over and starting again.' },
  { name: 'NEON', hex: '#b5ff61', where: 'SMILEY® PUMPKIN/NEON, HALTER® NEON/GOOD® BLUE', desc: 'Hello!!! We\'re here!!! NEON is our loudest statement and doesn\'t apologize for it. See us.' },
  { name: 'SAFETY', hex: '#ff5a1f', where: 'SMILEY® SAFETY/GOOD® BLUE', desc: 'A tasteful, vivid orange, the color of paying attention. A quiet nod to the care that goes into everything we make.' },
  { name: 'PEPSI', hex: ['#3730fe', '#ff141d'], where: 'GOODIE® PEPSI', desc: 'A pairing as old as contrast itself: fire and ice, good and evil, right and wrong. Or just a cold soda on a hot day.' },
  { name: 'OXBLOOD', hex: '#713a40', where: 'GOODIE® and G-KNIT® OXBLOOD/GOLDENROD, CORSET® OXBLOOD/GOLDENROD', desc: 'A deep, classic red for the discerning. Rich, grown-up, and a little literary. This is our take on it, made permanent.' },
  { name: 'GOLDENROD', pantone: 'PANTONE® 14-0951 TCX GOLDEN ROD', hex: '#e3a828', where: 'GOODIE® and G-KNIT® OXBLOOD/GOLDENROD, CORSET® OXBLOOD/GOLDENROD', desc: 'A warm, sunlit yellow from Pantone\'s library (PANTONE® 14-0951 TCX Golden Rod), named for the wildflower that lights up late-summer fields. Here it\'s the glow against OXBLOOD.' },
  { name: 'VANILLA BEAN', hex: '#ece4d2', where: 'G-KNIT® VANILLA BEAN/GOOD® BLUE', desc: 'Not white, not yellow: the warm, speckled cream of the real thing, scraped from the pod. Soft and a little golden, the quiet ground a pattern needs to be heard.' },
  { name: 'STRAWBERRY MILK', hex: '#f6c6d4', where: 'CARDIE® STRAWBERRY MILK/TOMATO VINE', desc: 'The pink left at the bottom of the glass. Sweet without trying, soft as a Saturday morning, and a little bit nostalgic. Pair it with TOMATO VINE and you have a whole watermelon.' },
  { name: 'CREAMSICLE', hex: '#fcc9a2', where: 'CARDIE® CREAMSICLE/TOMATO VINE', desc: 'Orange sherbet melting into vanilla on a hot afternoon, eaten too fast off the stick. A pastel with a little sun still in it.' },
  { name: 'MARSHMALLOW', hex: '#f7f2ea', where: 'CARDIE® MARSHMALLOW/TOMATO VINE', desc: 'A white that went soft. Warmer than COTTON, puffier, toasted just slightly at the edges. Comfort you can see.' },
  { name: 'TWEETIE', hex: '#ffd92e', where: 'CARDIE® TWEETIE/TOMATO VINE', desc: 'A bright, chirpy yellow that can’t sit still. Morning light through the window, a whistle before breakfast, and a little bit of mischief.' },
  { name: 'MATCHA', hex: '#9bb77a', where: 'CROPPED PUFFER® MATCHA/GOOD® BLUE', desc: 'Whisked, not steeped. A soft, grassy green with a little bitterness at the back, calm enough for a slow morning.' },
  { name: 'LILAC HAZE', hex: '#b9a3d9', where: 'CROPPED PUFFER® LILAC HAZE/GOOD® BLUE', desc: 'The purple of a late spring evening when the light won’t quite leave. Hazy, a little dreamy, and in no hurry.' },
  { name: 'BUTTERSCOTCH', hex: '#e0a24a', where: 'CROPPED PUFFER® BUTTERSCOTCH/GOOD® BLUE', desc: 'Brown sugar melted into butter and left to go golden. Warm, sticky-sweet, and a little old-fashioned.' },
  { name: 'GLACIER', hex: '#bcd9e6', where: 'CROPPED PUFFER® GLACIER/GOOD® BLUE', desc: 'Ice that has been blue for ten thousand years. Cold, clear and very, very patient.' },
  { name: 'DUCK CANVAS', hex: '#b98f55', where: 'CHORE COAT® DUCK CANVAS', desc: 'The tan of heavy cotton duck, the cloth workwear was built on. Stiff on day one, perfect by day one hundred.' },
  { name: 'BLACK RINSE', hex: '#26272d', where: 'CHORE COAT® BLACK RINSE', desc: 'Black denim rinsed once and never again. Deep, nearly inky, and quietly sharp.' },
  { name: 'ECRU TWILL', hex: '#ddd2b8', where: 'CHORE COAT® ECRU TWILL', desc: 'Undyed twill, the colour cotton is before anyone touches it. Honest, pale, and a little rustic.' },
  { name: 'FERN', hex: '#4f6b45', where: 'CHORE COAT® FERN', desc: 'The green under the canopy, where the light comes through in pieces. A working green, steady and shaded.' },
  { name: 'VOLT', hex: '#c8ff2e', where: 'SLICKER® VOLT', desc: 'A green-yellow you can hear. Built to be seen through the rain, the fog and the crowd.' },
  { name: 'HOT FLAMINGO', hex: '#ff4fb3', where: 'SLICKER® HOT FLAMINGO', desc: 'Pink turned all the way up and standing on one leg. Unapologetic, tropical, a little ridiculous, in the best way.' },
  { name: 'ELECTRIC TANGERINE', hex: '#ff7a1a', where: 'SLICKER® ELECTRIC TANGERINE', desc: 'Citrus with a current running through it. Bright, juicy, and wired.' },
  { name: 'ULTRAVIOLET', hex: '#8a3dff', where: 'SLICKER® ULTRAVIOLET', desc: 'Just past the edge of what you can see, brought back so you can. A violet that glows under any light.' },
  { name: 'OATMILK', hex: '#e7dcc8', where: 'FLEECE® OATMILK/COCOA', desc: 'The creamy beige of a morning latte. Soft, neutral and endlessly agreeable.' },
  { name: 'COCOA', hex: '#5a3a2a', where: 'FLEECE® OATMILK/COCOA', desc: 'Dark, bittersweet and warm. The colour of a hot drink held with both hands.' },
  { name: 'PEBBLE', hex: '#a9a59c', where: 'FLEECE® PEBBLE/TERRACOTTA', desc: 'A smooth grey stone from the riverbed, warmed by the sun. Quiet and grounded.' },
  { name: 'TERRACOTTA', hex: '#c7623f', where: 'FLEECE® PEBBLE/TERRACOTTA', desc: 'Baked earth: flowerpots, rooftops and old tiles. Warm, dusty, and made to last.' },
  { name: 'SAGE', hex: '#a7b59a', where: 'FLEECE® SAGE/FOREST', desc: 'A pale, silvery green, like the herb crushed between your fingers. Calming, and a little earthy.' },
  { name: 'FOREST', hex: '#2f4a33', where: 'FLEECE® SAGE/FOREST', desc: 'The deepest green in the woods, where the trees close in overhead. Dark, cool and quiet.' },
  { name: 'BERRY', hex: '#8a2a4b', where: 'FLEECE® BERRY/PEONY', desc: 'Crushed blackberries and red wine. Rich, deep, and just a little jammy.' },
  { name: 'PEONY', hex: '#f2a7c0', where: 'FLEECE® BERRY/PEONY', desc: 'Fat pink petals in early summer. Romantic without being shy about it.' },
  { name: 'SKY', hex: '#8fd0ff', where: 'GOODIE® SKY/COTTON, BABY TEE® and HALTER® SKY/COTTON, CARDIE® SKY/TOMATO VINE', desc: 'Look up on a nice day, when you can stare without being blinded or melted. That\'s SKY.' },
  { name: 'BLACK', hex: '#161616', where: 'GOODIE® BLACK/CHROME, HALTER® and CORSET® BLACK/CHROME', desc: 'GOOD®\'s interpretation of black: somewhere between slate and void. A look into nothing and everything at once. Or, put simply, just a good black.' },
  { name: 'CHROME', hex: '#c9ced6', where: 'GOODIE® BLACK/CHROME, MOSAIC® GRAY/CHROME, HALTER® and CORSET® BLACK/CHROME', desc: 'How do you draw silver in two dimensions, one block at a time? This is our best answer.' },
  { name: 'ROSE QUARTZ', pantone: 'PANTONE® 13-1520 TCX ROSE QUARTZ', hex: '#f7cac9', where: "GOODIE® I'M SOWWY (archive)", desc: 'One half of Pantone\'s first-ever dual Color of the Year (2016). Pantone describes it as a warm, embracing rose: gentle and compassionate, a feeling of calm. The softer side of I\'M SOWWY.' },
  { name: 'SERENITY', pantone: 'PANTONE® 15-3919 TCX SERENITY', hex: '#92a8d1', where: "GOODIE® I'M SOWWY (archive)", desc: 'The other half of Pantone\'s 2016 Color of the Year. In Pantone\'s words, a cooler, tranquil blue that brings a soothing sense of order and peace. Paired with ROSE QUARTZ, it\'s balance.' },
  { name: 'SPRINGSTEEN', hex: '#37baf7', where: 'JEAN® wash', desc: 'Nothing is more American than jeans. This wash recreates the classic Americana of Bruce Springsteen: grit, determination, and old-school cool. Decades old, still relevant.' },
  { name: 'ROADWORN', hex: '#6285b0', where: 'JEAN® wash', desc: 'Jeans tossed from the bed to your body, rolled around on a stage, left on someone\'s floor after a long night. Every good scar is in this wash.' },
  { name: 'FAVORITE JEANS', hex: '#86a6c4', where: 'JEAN® wash', desc: 'Our most neutral wash. There\'s not much to say about it, except that it was hard to find. We\'re glad we did.' },
  { name: 'THE JEAN', hex: '#3d5886', where: 'JEAN® wash', desc: 'Sort of the middle, but not quite. Casual? Preppy? Dressed up or down? The answer is yes.' },
  { name: 'PATENT', hex: '#283b62', where: 'JEAN® wash', desc: 'The color of selvedge denim just starting to wear in: almost broken in, still holding its original sheen. Do not wash with other clothes.' },
  { name: 'SELVEDGE', hex: '#161d3a', where: 'JEAN® wash', desc: 'Hot off the loom and made with care. The color of a brand-new pair: deep, luxurious, glossy, and full of shape.' },
  { name: 'HEATHER GREY', hex: '#9a9ca3', where: 'PLTSWT® HEATHER GREY', desc: 'The grey of a well-loved sweatshirt: flecked, soft, and quietly expensive. Made for PLTSWT®, where comfort gets a pressed pleat and a little ambition.' },
  { name: 'GRAY', hex: '#56565a', where: 'MOSAIC® GRAY/CHROME', desc: 'A mineral, matter-of-fact grey, the concrete under the MOSAIC®. Neutral enough to disappear, confident enough not to.' },
  { name: 'TOBACCO', hex: '#b57a36', where: 'Shoe: JEAN®, MOSAIC®, WATERMELONS®', desc: 'Warm, oiled leather after years of good walks. A brown with a story, spelled out in scuffs, creases and patina.' },
  { name: 'BROWN SHOE', hex: '#5a1e14', where: 'Shoe: JEAN®', desc: 'A deep, polished brown with a little red in its blood. The shoe you wear when you mean it.' },
  { name: 'BLACK SHOE', hex: '#1b1b1f', where: 'Shoe: JEAN®, WATERMELONS®', desc: 'The dependable one. A black that goes with everything and never needs explaining.' },
  { name: 'RED TARTAN', hex: ['#c41c28', '#461012'], where: 'Boxer: JEAN® SAGGING', desc: 'A plaid with centuries of Highland history behind it, worn where only a few people will ever see it. The best secrets are the ones that peek out.' },
  { name: 'SPONGE', hex: '#ffe600', where: 'DEEP END® GOODIE® SQUARE', desc: 'Absorbent, optimistic, and almost aggressively cheerful. The yellow of someone who lives in a pineapple under the sea and loves his job. Are you ready? We\'re ready.' },
  { name: 'STARFISH PINK', hex: '#e45fc6', where: 'DEEP END® GOODIE® STAR', desc: 'The pink of a best friend who lives under a rock and has absolutely no plans today. Soft, sun-warmed, and blissfully unbothered.' },
  { name: 'TENTACLE TEAL', hex: '#1fc0ff', where: 'DEEP END® GOODIE® DROP', desc: 'A cool, slightly weary teal for the misunderstood artist next door. Plays a little clarinet, sighs a lot, secretly has great taste.' },
  { name: 'CLAW RED', hex: '#ff1a10', where: 'DEEP END® GOODIE® CLAW', desc: 'A bright, snappy red for a crustacean who loves money more than most people love anything. Loud, proud, and counting every penny.' },
  { name: 'KRAB RED', hex: '#d7261e', where: 'DEEP END® SHIRT® KRAB', desc: 'The red of the world\'s most famous fast-food uniform, worn with pride from the grill to the register. Order up.' },
  { name: 'TROUSER BROWN', hex: '#86341f', where: 'DEEP END® JEAN®', desc: 'Square pants, brown as the originals, pulled up high. Classic, a little goofy, entirely sincere.' },
  { name: 'SEAFOAM GREEN', hex: '#3a9a0a', where: 'DEEP END® JORT®', desc: 'A bright, leafy green for shorts that were never going to be serious. The seafloor on its best day.' },
  { name: 'DEEP TEAL', hex: '#0f7fa0', where: 'DEEP END® JEAN®', desc: 'The deep water just past the reef, where the light starts to fade. Muted, moody, and a touch dramatic.' },
  { name: 'ANCHOR BLUE', hex: '#4a40d8', where: 'DEEP END® JEAN®', desc: 'A steady, nautical blue for a sailor\'s working pants. Heavy enough to hold its ground when the tide pulls.' },
];
