// COLORS®: every colour GOOD® has released, shown on colors.html.
// Keep this list up to date: whenever a new colour ships (a shirt or pants
// colourway, a wash, a shoe, a DEEP END® look), add it here.
// hex = the colour (two for colours that are always worn as a pair);
// where = what it's used in; desc = the description shown on the page.
window.GOOD_COLORS = [
  { name: 'GOOD® BLUE', hex: '#0000ff', where: 'SHIRT®, CROPPIE®, SMILEY®, GOODIE®, COLLAR®, SNEAK01 sole', desc: '' },
  { name: 'COTTON', hex: '#ffffff', where: 'SHIRT®, CROPPIE®, SMILEY®, GOODIE®, COLLAR®', desc: '' },
  { name: 'DENIM', hex: '#57b3ea', where: 'SHIRT® COTTON/DENIM, COLLAR® COTTON/DENIM', desc: '' },
  { name: 'BLAUE', hex: '#2468ff', where: 'SHIRT® BLAUE/COTTON', desc: '' },
  { name: 'DUST PINK', hex: '#c98aa0', where: 'CROPPIE® DUST PINK/TOMATO VINE', desc: '' },
  { name: 'TOMATO VINE', hex: '#3f7a55', where: 'CROPPIE® DUST PINK/TOMATO VINE', desc: '' },
  { name: 'PUMPKIN', hex: '#fda327', where: 'SMILEY® PUMPKIN/NEON', desc: '' },
  { name: 'NEON', hex: '#b5ff61', where: 'SMILEY® PUMPKIN/NEON', desc: '' },
  { name: 'SAFETY', hex: '#ff5a1f', where: 'SMILEY® SAFETY/GOOD® BLUE', desc: '' },
  { name: 'PEPSI', hex: ['#3730fe', '#ff141d'], where: 'GOODIE® PEPSI', desc: '' },
  { name: 'OXBLOOD', hex: '#713a40', where: 'GOODIE® OXBLOOD/GOLDENROD', desc: '' },
  { name: 'GOLDENROD', hex: '#e3a828', where: 'GOODIE® OXBLOOD/GOLDENROD', desc: '' },
  { name: 'SKY', hex: '#8fd0ff', where: 'GOODIE® SKY/COTTON', desc: '' },
  { name: 'BLACK', hex: '#161616', where: 'GOODIE® BLACK/CHROME', desc: '' },
  { name: 'CHROME', hex: '#c9ced6', where: 'GOODIE® BLACK/CHROME, MOSAIC® GRAY/CHROME', desc: '' },
  { name: 'ROSE QUARTZ', hex: '#f7cac9', where: "GOODIE® I'M SOWWY (archive)", desc: '' },
  { name: 'SERENITY', hex: '#92a8d1', where: "GOODIE® I'M SOWWY (archive)", desc: '' },
  { name: 'SPRINGSTEEN®', hex: '#37baf7', where: 'JEAN® wash', desc: '' },
  { name: 'ROADWORN®', hex: '#6285b0', where: 'JEAN® wash', desc: '' },
  { name: 'FAVORITE JEANS®', hex: '#86a6c4', where: 'JEAN® wash', desc: '' },
  { name: 'THE JEAN®', hex: '#3d5886', where: 'JEAN® wash', desc: '' },
  { name: 'PATENT®', hex: '#283b62', where: 'JEAN® wash', desc: '' },
  { name: 'SELVEDGE®', hex: '#161d3a', where: 'JEAN® wash', desc: '' },
  { name: 'HEATHER GREY', hex: '#9a9ca3', where: 'PLTSWT® HEATHER GREY', desc: '' },
  { name: 'GRAY', hex: '#56565a', where: 'MOSAIC® GRAY/CHROME', desc: '' },
  { name: 'TOBACCO', hex: '#b57a36', where: 'Shoe: JEAN®, MOSAIC®', desc: '' },
  { name: 'BROWN SHOE', hex: '#5a1e14', where: 'Shoe: JEAN®', desc: '' },
  { name: 'BLACK SHOE', hex: '#1b1b1f', where: 'Shoe: JEAN®', desc: '' },
  { name: 'RED TARTAN', hex: ['#c41c28', '#461012'], where: 'Boxer: JEAN® SAGGING', desc: '' },
  { name: 'SPONGE', hex: '#ffe600', where: 'DEEP END® GOODIE® SQUARE', desc: '' },
  { name: 'STARFISH PINK', hex: '#e45fc6', where: 'DEEP END® GOODIE® STAR', desc: '' },
  { name: 'TENTACLE TEAL', hex: '#1fc0ff', where: 'DEEP END® GOODIE® DROP', desc: '' },
  { name: 'CLAW RED', hex: '#ff1a10', where: 'DEEP END® GOODIE® CLAW', desc: '' },
  { name: 'KRAB RED', hex: '#d7261e', where: 'DEEP END® SHIRT® KRAB', desc: '' },
  { name: 'TROUSER BROWN', hex: '#86341f', where: 'DEEP END® JEAN®', desc: '' },
  { name: 'SEAFOAM GREEN', hex: '#3a9a0a', where: 'DEEP END® JORT®', desc: '' },
  { name: 'DEEP TEAL', hex: '#0f7fa0', where: 'DEEP END® JEAN®', desc: '' },
  { name: 'ANCHOR BLUE', hex: '#4a40d8', where: 'DEEP END® JEAN®', desc: '' },
];
